### ISSUE TITLE
jonswap_spectrum bug

### ISSUE THREAD

**Issue by ckberinger** [MHKiT-Software/MHKiT-MATLAB#132] opened 2024-05-10 19:01 UTC
Hello,

I found a bug in the jonswap_spectrum code for MHKiT Matlab. The elseif nargin == 4 line has the gamma value placed into the Hs and gamma part of the function. This causes incorrect formulation of the Jonswap function. The correct code is below as the Hs needs to be in the Hs spot of the python function. The gamma value should only change the peakiness of the spectrum, this can be easily seen when plotting the spectrum.

```
elseif nargin == 4
        S_py=py.mhkit.wave.resource.jonswap_spectrum(frequency,Tp,Hs,pyargs('gamma',varargin{1}));
```

Cheers,
Courtney

**Comment by simmsa** [comment] 2024-05-10 20:57
@ckberinger, thank you for reporting this! I can reproduce this issue and have submitted #133 to test for and fix this bug. I will follow up with you after we review #133.

**Comment by simmsa** [comment] 2024-07-10 17:38
Hi @ckberinger, we believe fixed this in #136, and merged this fix into the v0.5.0 release yesterday. Let us know if this fixes your specific issue with the `jonswap_spectrum` function. 

One sidenote, this issue helped us troubleshoot an another issue with the WDRT additions included in the latest release that was caused by this bug. Thank you for reporting this!

**Comment by ckberinger** [comment] 2024-07-15 16:29
Hey @simmsa this looks great! I am glad it was able to help with another issue!

**Comment by simmsa** [comment] 2024-07-18 21:52
It is great to have your help! I am going to close this.

**Closed by simmsa** 2024-07-18 21:52 UTC
